/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.PrincipalController;

/**
 *
 * @author tulio
 */
public class Principal extends javax.swing.JFrame {

    private final PrincipalController controller;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        controller = new PrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastroUsuario = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnCadastroFilme = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProcuraFilme = new javax.swing.JButton();
        btnAlugar = new javax.swing.JButton();
        btnReceberFilmes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExibirUsuarios = new javax.swing.JButton();
        btnExibirClientes = new javax.swing.JButton();
        btnExibirFilmes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrarFatura = new javax.swing.JButton();
        btnExibirFaturamento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locadora is Not Dead");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastroUsuario.setText("Cadastrar Usuário");
        btnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnCadastroCliente.setText("Cadastrar Cliente");
        getContentPane().add(btnCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        btnCadastroFilme.setText("Cadastrar Filme");
        getContentPane().add(btnCadastroFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 450, 60));

        jLabel2.setText("Área de Cadastro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btnProcuraFilme.setText("Procurar Filme");
        getContentPane().add(btnProcuraFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, -1));

        btnAlugar.setText("Alugar");
        getContentPane().add(btnAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 130, -1));

        btnReceberFilmes.setText("Receber Filmes");
        getContentPane().add(btnReceberFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 120, -1));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 450, 60));

        jLabel4.setText("Área Administrativa");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btnExibirUsuarios.setText("Exibir Usuários");
        getContentPane().add(btnExibirUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, -1));

        btnExibirClientes.setText("Exibir Clientes");
        getContentPane().add(btnExibirClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));

        btnExibirFilmes.setText("Exibir Filmes");
        getContentPane().add(btnExibirFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 120, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 450, 60));

        jLabel6.setText("Área de Exibição");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        btnRegistrarFatura.setText("Registrar Fatura");
        getContentPane().add(btnRegistrarFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, -1));

        btnExibirFaturamento.setText("Exibir Faturamento");
        getContentPane().add(btnExibirFaturamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/locadora_1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 500));

        setSize(new java.awt.Dimension(502, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuarioActionPerformed
        controller.entrarCadastroUsuario();
    }//GEN-LAST:event_btnCadastroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlugar;
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroFilme;
    private javax.swing.JButton btnCadastroUsuario;
    private javax.swing.JButton btnExibirClientes;
    private javax.swing.JButton btnExibirFaturamento;
    private javax.swing.JButton btnExibirFilmes;
    private javax.swing.JButton btnExibirUsuarios;
    private javax.swing.JButton btnProcuraFilme;
    private javax.swing.JButton btnReceberFilmes;
    private javax.swing.JButton btnRegistrarFatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
